#!/usr/bin/env python3
"""Guard: every indexable page (singular AND section/home landing) owns its card.

Four failure classes are caught deterministically from the source tree (no Hugo
build needed), matching how ``layouts/_partials/head.html`` resolves ``og:image``:

  Check A - bundle form.  A singular content page must be a leaf bundle
    (``<slug>/index.<ext>``), never a flat ``<slug>.<ext>``.  A flat file cannot
    hold a co-located ``share-card.*``/``hero.*`` resource, so it silently falls
    back to the site default card.  This is the ``.md is not proper`` class (#52).
    Excludes ``_index.*`` (Hugo requires it for sections) and bundle-internal
    resources (a content file anywhere under a leaf-bundle dir tree).

  Check B - card presence (singular pages).  A singular indexable page's bundle
    must contain its own card, mirroring head.html exactly: a root
    ``share-card.<raster>`` wins; a root ``share-card.svg`` is a VIOLATION
    (head.html suppresses og:image for an SVG); otherwise a non-SVG raster hero
    anywhere in the bundle (but NOT inside a nested child bundle) qualifies;
    nothing => falls back to the default card.

  Check C - card presence (section + home landings, blog-priv#61).  Every
    indexable ``_index.*`` landing (a Hugo section, plus the home bundle) must own
    a root ``share-card.<raster>``.  Unlike Check B there is NO hero fallback:
    head.html's hero-pick is ``.IsPage``-only, so a section/home hero is never the
    og:image - only a root ``share-card.*`` counts, else it falls back to the
    default card.  The default card is thus reserved for taxonomy/term pages
    (which have no content bundle and cannot hold a card).

  Check D - card presence (auto-sections, blog-priv#61 2nd increment).  Hugo also
    renders a list page for a TOP-LEVEL content directory that has NO ``_index.*``.
    Check C enumerates ``_index.*`` landings only, so such a directory is invisible
    to it and silently serves the default card - which is how ``/posts/`` shipped the
    default until blog-priv#62 gave it a ``content/posts/_index.md``.  An
    auto-section CAN hold a card (Hugo still publishes the directory's files as page
    resources), so this checks card PRESENCE like Check C; the fix it recommends is
    the ``_index.*`` because ``gen_card.py landings`` reads each card's copy from
    that frontmatter.  Check D also covers HOME when ``content/_index.md`` is absent:
    Hugo still renders ``/``, but ``landing_bundles`` yields nothing for it, so Check
    C would silently stop covering the site's highest-traffic page.

``ext`` spans the content formats Hugo renders natively on this site: ``.md``,
``.markdown``, ``.html`` (CONTENT_EXTS).

Exclusions (a page legitimately using the shared default card is NOT a
violation), all deterministic:
  - taxonomy/term + tag pages: generated by Hugo with no ``content`` bundle, so
    they are never enumerated by Check B (leaf bundles) or Check C (``_index.*``
    landings) and keep the shared default card.
  - noindex pages: any path matched by an ``X-Robots-Tag: noindex|none`` rule in
    ``static/_headers`` (the source of truth, fnmatch against the page's served
    URL honouring a ``url:`` / ``slug:`` frontmatter override), or frontmatter
    ``noindex`` / ``sitemap.disable`` / ``draft`` / ``headless`` / build render
    ``never`` (e.g. ``content/private``).

Optional ground-truth backstop (``--built <public-dir>``): after a Hugo build,
re-checks each singular indexable page's RENDERED ``og:image`` and fails if it is
the site default / mug.  This catches a head.html/hero-pick TEMPLATE regression
that the source heuristic (which re-implements that logic in Python) cannot see.

Usage:  python3 scripts/check_social_cards.py [--content DIR] [--headers FILE]
        python3 scripts/check_social_cards.py --built public [--content DIR]
Exit:   0 = clean, 1 = violations, 2 = read/setup error
"""
from __future__ import annotations

import argparse
import fnmatch
import re
import sys
from itertools import chain
from pathlib import Path

CONTENT_EXTS = (".md", ".markdown", ".html")   # Hugo natively-rendered content files
RASTER_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
DEFAULT_CARD_MARKERS = ("default-card", "hoi-mug")   # og:image URLs that ARE the site default

# The remedy every violation message points at. Deliberately the wrapper, never a bare
# `gen_card.py <set>`: a card's eyebrow is read from the page's public/<url>/trail.json
# sidecar, which only exists once Hugo has rendered that page. The commonest way to hit
# this guard is to add a NEW landing and run the checks before any build, and in exactly
# that state `gen_card.py` exits non-zero from card_common.eyebrow_for ("no trail.json
# for content bundle ..."). Sending the reader to the bare generator therefore bounces
# them into a second, unrelated-looking error. gen-social-cards.sh builds first, so it
# works from a cold tree. (blog-priv#61, Ralph T3 finding F6.)
REGEN_CMD = "scripts/gen-social-cards.sh"


def read_frontmatter(path: Path) -> str:
    """Return the raw YAML frontmatter block (between the first two --- lines)."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = re.match(r"^---\n(.*?)\n---", text, re.S)
    return m.group(1) if m else ""


def index_file(dirpath: Path) -> Path | None:
    """The leaf-bundle index (index.md/index.markdown/index.html) in dirpath, or None."""
    for ext in CONTENT_EXTS:
        p = dirpath / ("index" + ext)
        if p.exists():
            return p
    return None


def _under_a_bundle(path: Path, content_root: Path) -> bool:
    """True if any ancestor dir (below content_root) is a leaf bundle => path is a resource."""
    d = path.parent
    while True:
        if index_file(d):
            return True
        if d == content_root or d.parent == d:
            return False
        d = d.parent


def _in_child_bundle(bundle_dir: Path, f: Path) -> bool:
    """True if f lives inside a NESTED child leaf bundle under bundle_dir (Hugo scopes
    a child bundle's resources to the child page, not the parent's og:image)."""
    d = f.parent
    while d != bundle_dir:
        if index_file(d):
            return True
        d = d.parent
    return False


# Robots directives that TAKE a value, so the text after their colon is a
# parameter and never an indexing instruction. `max-image-preview:none` limits
# preview image size; it says nothing about indexing. Matching a bare `none`
# anywhere in the header value read that as "this page is noindexed" and
# reported a fully indexable page as protected (blog-priv#64, Ralph round 5).
_VALUED_DIRECTIVES = frozenset({
    "max-snippet", "max-image-preview", "max-video-preview", "unavailable_after",
})


def _is_noindex_value(value: str) -> bool:
    """True when an `X-Robots-Tag` value actually asks for no indexing.

    The value is a comma-separated directive list. A directive is either bare
    (`noindex`, `nofollow`, `none`, `all`), valued (`max-image-preview:none`),
    or bare behind a user-agent prefix (`googlebot: noindex`). Both of the last
    two contain a colon, so the key is what tells them apart.
    """
    for raw_directive in value.split(","):
        directive = raw_directive.strip().lower()
        if not directive:
            continue
        if ":" in directive:
            key, _, rest = directive.partition(":")
            if key.strip() in _VALUED_DIRECTIVES:
                continue                             # a parameter, not a verdict
            directive = rest.strip()                 # a user-agent prefix
        if directive in ("noindex", "none"):
            return True
    return False


def parse_noindex_globs(headers_path: Path) -> list[str]:
    """Path globs that static/_headers marks noindex (X-Robots-Tag: noindex|none)."""
    if not headers_path.exists():
        return []
    globs: list[str] = []
    current: str | None = None
    # utf-8-sig, not utf-8: a leading BOM makes the first line start with U+FEFF
    # rather than "/", so the first block's path line is not recognised and its
    # rule is dropped silently. The reachable path is mundane - alphabetise the
    # blocks in this file (`/404*` sorts first) and save from any BOM-emitting
    # editor on Windows - and it costs the 404 page its noindex with every gate
    # still green (blog-priv#64, Ralph round 6).
    for raw in headers_path.read_text(encoding="utf-8-sig").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if raw.startswith("/"):                      # a path-glob line
            current = raw.strip()
            continue
        header, sep, value = raw.partition(":")
        if current and sep and header.strip().lower() == "x-robots-tag" \
                and _is_noindex_value(value):
            globs.append(current)
            current = None                           # one match per block is enough
    return globs


def _url_matches(url: str, glob: str) -> bool:
    """fnmatch a served URL against a Cloudflare _headers glob (handles /foo/*, /a/*/b)."""
    return fnmatch.fnmatch(url, glob) or fnmatch.fnmatch(url.rstrip("/"), glob.rstrip("/*"))


def load_url_index(public: Path) -> dict[str, str]:
    """content-bundle key -> served URL, read from Hugo's own per-page trail.json.

    This is the ONLY authority on where a page is served. Deriving it from the
    content path (see page_url's fallback) re-implements Hugo's permalink
    resolution in Python, and blog-priv#62 is exactly the change that breaks such
    a re-implementation: `[permalinks.page] posts = "/blogs/:slugorcontentbasename/"`
    means content/posts/<dir>/ is served at /blogs/<slug>/, which no amount of
    frontmatter-reading recovers from the path alone.

    Reuses the generators' index (scripts/social-cards/card_common.py) rather than
    a second copy, so the card pipeline and this guard resolve URLs identically.

    `required=False`: a tree with no sidecars yields {} rather than a hard exit. The
    generators cannot proceed without trails (no eyebrow can be derived) but this
    guard can: it degrades to the content-path fallback, and `--strict` then names
    every page whose derived URL the build does not serve. Exiting here instead
    would also break every synthetic --built fixture, which is a fabricated tree
    with no Hugo output in it.
    """
    sys.path.insert(0, str(Path(__file__).resolve().parent / "social-cards"))
    from card_common import load_trails                      # noqa: PLC0415
    trails = load_trails(public, required=False)
    if not trails:
        print(f"warning: no trail.json sidecars under {public}; served URLs fall back "
              f"to content-path derivation, which is not permalink-aware. Use --strict "
              f"to turn every unresolved page into a failure.", file=sys.stderr)
    return {key: (entry.get("url") or "") for key, entry in trails.items()}


def page_url(index_path: Path, content_root: Path, fm: str,
             url_index: dict[str, str] | None = None) -> str:
    """Served URL for a content page.

    With `url_index` (from load_url_index), Hugo's own answer wins. Without it,
    falls back to: frontmatter `url:` override, else a `slug:` override on the
    leaf segment, else the directory path.

    The fallback is NOT permalink-aware and is wrong for anything under a
    [permalinks] rule. It survives because the source-only mode has no build to
    read, and because `--built --strict` turns any page whose derived URL is not
    actually served into a named [rendered-missing] failure rather than the
    silent skip that let a wrong derivation pass 87 pages while CI stayed green.
    """
    if url_index is not None:
        key = index_path.parent.relative_to(content_root).as_posix()
        key = "" if key == "." else key
        served = url_index.get(key)
        if served:
            return served if served.endswith("/") else served + "/"
    m = re.search(r'^url:\s*["\']?([^"\'\n]+?)["\']?\s*$', fm, re.M)
    if m:
        url = m.group(1).strip()
        return url if url.endswith("/") else url + "/"
    parts = list(index_path.parent.relative_to(content_root).parts)
    sm = re.search(r'^slug:\s*["\']?([^"\'\n]+?)["\']?\s*$', fm, re.M)
    if sm and parts:
        parts[-1] = sm.group(1).strip()
    rel = "/".join(parts)
    return "/" + rel + "/" if rel else "/"


def is_excluded(fm: str, url: str, noindex_globs: list[str]) -> bool:
    """A page legitimately using the default card (or not rendered) is not a violation."""
    if re.search(r"^draft:\s*true\s*$", fm, re.M):
        return True
    if re.search(r"^noindex:\s*true\s*$", fm, re.M):
        return True
    if re.search(r"^headless:\s*true\s*$", fm, re.M):
        return True
    if re.search(r"sitemap:\s*\n\s+disable:\s*true", fm):
        return True
    if re.search(r"render:\s*['\"]?never", fm):       # _build.render / build.render: never
        return True
    return any(_url_matches(url, g) for g in noindex_globs)


def card_status(bundle_dir: Path) -> str:
    """Mirror head.html's og:image resolution for a leaf bundle.

    Returns 'ok' (a real card renders), 'svg-sharecard' (a root share-card.svg wins
    and head.html emits NOTHING), or 'none' (falls back to the default card)."""
    share_svg = False
    for f in bundle_dir.iterdir():                    # root-level share-card.* only (GetMatch pattern)
        if f.is_file() and f.name.startswith("share-card."):
            if f.suffix.lower() in RASTER_EXTS:
                return "ok"
            if f.suffix.lower() == ".svg":
                share_svg = True
    if share_svg:
        return "svg-sharecard"
    for f in bundle_dir.rglob("*"):                   # hero: any non-SVG raster, excl. child bundles
        if f.is_file() and f.suffix.lower() in RASTER_EXTS and not _in_child_bundle(bundle_dir, f):
            return "ok"
    return "none"


def leaf_bundles(content_root: Path):
    """Yield (bundle_dir, index_path) for every leaf-bundle page under content_root."""
    seen = set()
    for f in sorted(content_root.rglob("*")):
        if f.is_dir():
            idx = index_file(f)
            if idx and f not in seen:
                seen.add(f)
                yield f, idx


def flat_pages(content_root: Path):
    """Yield every flat singular content page (Check A violation candidate)."""
    for f in sorted(content_root.rglob("*")):
        if not f.is_file() or f.suffix.lower() not in CONTENT_EXTS:
            continue
        if f.stem in ("index", "_index"):
            continue
        if _under_a_bundle(f, content_root):          # a bundle resource, not a page
            continue
        yield f


def section_index_file(dirpath: Path) -> Path | None:
    """The section/home branch-bundle index (_index.md/_index.markdown/_index.html), or None."""
    for ext in CONTENT_EXTS:
        p = dirpath / ("_index" + ext)
        if p.exists():
            return p
    return None


def landing_bundles(content_root: Path):
    """Yield (bundle_dir, index_path) for every section + home landing (_index.*) under
    content_root, INCLUDING the home bundle (content_root itself). These are Hugo section
    and home pages; head.html resolves their og:image from a root share-card.* only (the
    site default card otherwise), so every indexable landing must own a card (Check C)."""
    for f in sorted(content_root.rglob("*")):
        if f.is_dir():
            idx = section_index_file(f)
            if idx:
                yield f, idx
    home_idx = section_index_file(content_root)       # content/_index.md - not in rglob("*")
    if home_idx:
        yield content_root, home_idx


def auto_sections(content_root: Path):
    """Yield every TOP-LEVEL content directory Hugo renders as a section list page
    with NO ``_index.*`` to back it (a Hugo "auto-section").

    Check C only enumerates ``_index.*`` landings, so an auto-section is invisible to
    it and silently serves the site default card. That is exactly how ``/posts/``
    shipped the default card until blog-priv#62 gave it a ``content/posts/_index.md``.

    An auto-section CAN hold a card: Hugo still publishes the directory's files as
    page resources, so a root ``share-card.<raster>`` does become the ``og:image``.
    Verified against a real build - a probe directory with a ``share-card.png`` and no
    ``_index.md`` rendered ``og:image`` = its own ``share-card_hu_<hash>.jpg``, not the
    default. So this check tests card PRESENCE (like Check C), not ``_index.*``
    absence; a carded auto-section is not a violation.

    The practical remedy is still to add the ``_index.*``, because
    ``gen_card.py landings`` sources each card's title and tagline from the landing's
    own frontmatter and an auto-section has none.

    **Only depth-1 directories qualify.** Hugo makes a directory a section when it is
    top-level OR carries an ``_index.*`` - a NESTED directory without one is not a
    section at all, and its pages belong to the ancestor section. Measured on the
    pinned Hugo (0.160.0 extended): with ``content/toplevel/deeper/pageC/index.md``
    and ``content/parent/nested/pageB/index.md``, the build rendered ``/toplevel/``
    (kind=section) and ``/parent/`` (kind=section) but emitted NO page for
    ``/toplevel/deeper/`` or ``/parent/nested/``. Walking every ancestor would flag
    directories Hugo never serves and assert something false about them.

    ``content_root`` is not yielded here; home is handled separately in ``check()``
    because it needs no depth rule and its URL is always ``/``."""
    for d in sorted(p for p in content_root.iterdir() if p.is_dir()):
        if index_file(d):                             # a leaf bundle is a page, not a section
            continue
        if section_index_file(d):                     # backed by _index.* -> Check C owns it
            continue
        if _holds_a_page(d, content_root):            # an empty/asset-only dir is not a section
            yield d


def _holds_a_page(dirpath: Path, content_root: Path) -> bool:
    """True if `dirpath` contains at least one real content page beneath it. A
    top-level directory with no pages (e.g. an asset-only folder) is not rendered as
    a section, so it is not an auto-section either."""
    for f in dirpath.rglob("*"):
        if not f.is_file() or f.suffix.lower() not in CONTENT_EXTS:
            continue
        if f.stem in ("index", "_index") or not _under_a_bundle(f, content_root):
            return True
    return False


def section_dir_url(dirpath: Path, content_root: Path,
                    url_index: dict[str, str] | None = None) -> str:
    """Served URL for an auto-section directory.

    With `url_index` (from load_url_index) Hugo's own answer wins - the same contract
    `page_url` uses, and for the same reason: a ``[permalinks.section]`` rule means the
    content path is NOT the served path (blog-priv#62 maps ``posts`` to ``/blogs/``),
    so deriving the URL from the directory name re-implements Hugo's permalink
    resolution and gets it wrong. That matters here because the noindex exclusion
    fnmatches this URL against ``static/_headers``: a wrong URL both false-positives on
    a rule written for the real path and silently skips on a stale one.

    The content-path fallback exists only for source-only mode, where there is no
    build to read; ``--built --strict`` is what turns an unresolved page into a
    named failure rather than a silent skip."""
    rel = dirpath.relative_to(content_root).as_posix()
    if url_index is not None:
        served = url_index.get("" if rel == "." else rel)
        if served:
            return served if served.endswith("/") else served + "/"
    return "/" + rel + "/" if rel != "." else "/"


def landing_card_status(bundle_dir: Path) -> str:
    """og:image resolution for a section/home landing: a root share-card.<raster> wins
    ('ok'); a root share-card.svg emits NO og:image ('svg-sharecard'); anything else
    falls back to the site default card ('none'). Unlike card_status (leaf pages) there is
    NO hero fallback - head.html's hero-pick is .IsPage-only, so a section/home hero is
    never the og:image, and the whole-bundle rglob is skipped (it would recurse the entire
    content tree for the home bundle)."""
    share_svg = False
    for f in bundle_dir.iterdir():                    # root-level share-card.* only
        if f.is_file() and f.name.startswith("share-card."):
            if f.suffix.lower() in RASTER_EXTS:
                return "ok"
            if f.suffix.lower() == ".svg":
                share_svg = True
    return "svg-sharecard" if share_svg else "none"


def check(content_root: Path, headers_path: Path,
          url_index: dict[str, str] | None = None) -> list[str]:
    violations: list[str] = []
    noindex_globs = parse_noindex_globs(headers_path)

    for f in flat_pages(content_root):
        rel = f.relative_to(content_root).as_posix()
        stem = f.parent / f.stem
        violations.append(
            f"[bundle-form] {rel}: flat page must be a leaf bundle "
            f"({stem.relative_to(content_root).as_posix()}/index{f.suffix}) so it can hold a share-card"
        )

    for bundle_dir, index_path in leaf_bundles(content_root):
        fm = read_frontmatter(index_path)
        url = page_url(index_path, content_root, fm)
        if is_excluded(fm, url, noindex_globs):
            continue
        rel = index_path.relative_to(content_root).as_posix()
        status = card_status(bundle_dir)
        if status == "svg-sharecard":
            violations.append(
                f"[card-svg] {rel} ({url}): share-card is an SVG; head.html emits NO "
                f"og:image for an SVG. Use a raster share-card.png (run {REGEN_CMD})."
            )
        elif status == "none":
            violations.append(
                f"[card-missing] {rel} ({url}): no share-card.* or raster hero; "
                f"falls back to the default card. Run {REGEN_CMD}, or add a hero.*"
            )

    for bundle_dir, index_path in landing_bundles(content_root):
        fm = read_frontmatter(index_path)
        url = page_url(index_path, content_root, fm)
        if is_excluded(fm, url, noindex_globs):       # noindex / render:never / draft landings
            continue
        rel = index_path.relative_to(content_root).as_posix()
        status = landing_card_status(bundle_dir)
        if status == "svg-sharecard":
            violations.append(
                f"[landing-card-svg] {rel} ({url}): share-card is an SVG; head.html emits NO "
                f"og:image for an SVG. Use a raster share-card.png (run {REGEN_CMD})."
            )
        elif status == "none":
            violations.append(
                f"[landing-card-missing] {rel} ({url}): indexable section/home landing has no "
                f"share-card.*; falls back to the default card. Add it to landing-cards.tsv and "
                f"run {REGEN_CMD}."
            )

    # Home with no content/_index.md: Hugo still renders "/", but landing_bundles
    # yields nothing for it, so Check C silently stops covering the highest-traffic
    # page. Verified: a tree with no content/_index.md renders kind=home at / serving
    # default-card, and the guard passed before this clause existed.
    if not section_index_file(content_root):
        home_url = section_dir_url(content_root, content_root, url_index)
        if not is_excluded("", home_url, noindex_globs):
            status = landing_card_status(content_root)
            if status != "ok":
                violations.append(
                    f"[auto-section-uncarded] . ({home_url}): the site has no "
                    f"content/_index.md, so Hugo renders home from no content file and "
                    f"Check C cannot enumerate it; it serves the default card. Add "
                    f"content/_index.md, then run {REGEN_CMD}."
                )

    for section_dir in auto_sections(content_root):
        url = section_dir_url(section_dir, content_root, url_index)
        if is_excluded("", url, noindex_globs):       # no frontmatter exists; _headers decides
            continue
        rel = section_dir.relative_to(content_root).as_posix()
        status = landing_card_status(section_dir)
        if status == "svg-sharecard":
            violations.append(
                f"[auto-section-card-svg] {rel} ({url}): share-card is an SVG; head.html emits "
                f"NO og:image for an SVG. Use a raster share-card.png (run {REGEN_CMD})."
            )
        elif status == "none":
            violations.append(
                f"[auto-section-uncarded] {rel} ({url}): Hugo renders this directory as an "
                f"indexable section list page, but it has no _index.* so Check C cannot see it "
                f"and it owns no share-card - it serves the default card. Add {rel}/_index.md "
                f"(title + description, which is where gen_card.py reads the card copy from), "
                f"then add '{rel}' to scripts/social-cards/landing-cards.tsv and run "
                f"{REGEN_CMD}."
            )
    return violations


def check_built(content_root: Path, headers_path: Path, public: Path,
                strict: bool = False) -> list[str]:
    """Ground-truth backstop: assert each singular indexable page's RENDERED og:image
    is not the site default. Catches head.html/hero-pick template regressions.

    `strict` turns a page whose rendered HTML cannot be found into a FAILURE instead
    of a skip. The lenient default exists for alias/permalink edges the source check
    owns, but it also means a wrong url-derivation silently skips every page it
    mis-resolves while this guard still reports OK — so any pipeline that depends on
    this check actually covering the site (scripts/gen-social-cards.sh) passes
    --strict. See blog-priv#62 AC 5.8."""
    violations: list[str] = []
    noindex_globs = parse_noindex_globs(headers_path)
    og_re = re.compile(r'<meta property="og:image" content="([^"]+)"')
    url_index = load_url_index(public)

    def verify_rendered(url: str) -> None:
        rendered = public / url.strip("/") / "index.html"
        if not rendered.exists():
            if strict:
                violations.append(
                    f"[rendered-missing] {url}: no rendered page at {rendered}, so its "
                    f"og:image was never checked (page_url() derived a URL the build does "
                    f"not serve, or the page did not render)."
                )
            return                                    # alias/permalink edge — source check owns it
        html = rendered.read_text(encoding="utf-8", errors="replace")
        m = og_re.search(html)
        og = m.group(1) if m else ""
        if not og or any(mk in og for mk in DEFAULT_CARD_MARKERS):
            violations.append(
                f"[rendered-default] {url}: rendered og:image is the site default "
                f"({og or 'MISSING'}); a real page must render its own card "
                f"(template regression or missing card)."
            )

    for bundle_dir, index_path in chain(leaf_bundles(content_root), landing_bundles(content_root)):
        fm = read_frontmatter(index_path)
        url = page_url(index_path, content_root, fm, url_index)
        if is_excluded(fm, url, noindex_globs):
            continue
        verify_rendered(url)

    # Auto-sections render too, and are exactly the kind Check D was added to protect,
    # so the template-regression backstop must cover them as well (they were omitted
    # from this chain when Check D first landed).
    for section_dir in auto_sections(content_root):
        url = section_dir_url(section_dir, content_root, url_index)
        if is_excluded("", url, noindex_globs):
            continue
        verify_rendered(url)
    return violations


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--content", default="content", help="content root (default: content)")
    ap.add_argument("--headers", default="static/_headers", help="path to static/_headers")
    ap.add_argument("--built", metavar="PUBLIC_DIR",
                    help="also verify rendered og:image in this Hugo build output dir")
    ap.add_argument("--strict", action="store_true",
                    help="with --built: a page whose rendered HTML is not found is a "
                         "FAILURE, not a silent skip")
    args = ap.parse_args()

    if args.strict and not args.built:
        ap.error("--strict only applies with --built")

    content_root = Path(args.content)
    if not content_root.is_dir():
        print(f"error: content root not found: {content_root}", file=sys.stderr)
        return 2
    headers_path = Path(args.headers)

    try:
        public = None
        if args.built:
            public = Path(args.built)
            if not public.is_dir():
                print(f"error: --built dir not found: {public}", file=sys.stderr)
                return 2
        # With a build available, hand the source check Hugo's own URL index so the
        # noindex exclusion fnmatches the URL Hugo really serves, not one derived from
        # the content path (a [permalinks.section] rule makes those differ).
        violations = check(content_root, headers_path,
                           load_url_index(public) if public else None)
        if public:
            violations += check_built(content_root, headers_path, public, strict=args.strict)
    except OSError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    if violations:
        print("Social-card guard: violations found\n", file=sys.stderr)
        for v in violations:
            print("  " + v, file=sys.stderr)
        print(f"\n{len(violations)} violation(s).", file=sys.stderr)
        return 1
    scope = ("source + rendered (strict)" if args.strict else "source + rendered") if args.built else "source"
    print(f"Social-card guard: OK ({scope}; every indexable page - singular, "
          f"section/home landing, auto-section - owns its card).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
