#!/usr/bin/env python3
"""Validate internal markdown links against the Hugo permalink contract.

Posts live at ``/blogs/<slug>/`` and category landings at ``/blogs/<category>/``
(blog-priv#62 moved both under ``/blogs/``; the retired root-level URLs are 301'd
in ``static/_redirects``). A landing LISTS the posts in its category, it does not
HOST them, so ``/blogs/dance/some-post/`` is broken even though it looks
plausible.

``<slug>`` is the SERVED slug, which is not always the bundle directory name: a
post's frontmatter ``slug:`` overrides it (``content/posts/2026-04-07-foundation/``
is served at ``/blogs/foundation/``). Resolution goes through that mapping, so a
link to a slug-overridden post is accepted and a link to its directory name is
not — matching what the site actually serves.

Lychee cannot catch this bug class: ``lychee.toml`` excludes
``content/posts`` (raw-markdown false-positive avoidance) and excludes
``hoiboy.uk`` URLs (Cloudflare race protection), so broken in-content
links to nonexistent paths are structurally invisible to the existing
link checker. This validator closes that gap.

Decision matrix (default = PASS):
  link is anchor-only / mailto / external / shortcode internals  -> SKIP
  link path is /blogs/<slug>/ AND that slug is served            -> PASS
  link path is /blogs/<category>/ (a category landing)           -> PASS
  link path is /blogs/ or /blogs/[<category>/]index.xml          -> PASS
  link path matches an allow-list entry                          -> PASS
  link path is a RETIRED /posts/... or /<category>/... URL       -> FAIL
  link path is /blogs/<category>/<slug>/                         -> FAIL
  link path is /blogs/<slug>/ AND no post serves that slug       -> FAIL
  any other / unrecognised internal path                         -> FAIL

Exit codes: 0 = pass, 1 = violations, 2 = read error
"""

from __future__ import annotations

import argparse
import re
import sys
from functools import lru_cache
from pathlib import Path

# The 7 blog categories. They are content sections whose landings are served
# under /blogs/ (config/_default/hugo.toml [permalinks.section], blog-priv#62).
# They are deliberately NOT in _ALLOW_SINGLE: a root-level /tech-ai/ link is a
# retired URL that now only survives via a 301, and an in-repo link should point
# at the live path rather than take a redirect hop.
_SECTIONS = (
    "adventure",
    "dance",
    "entrepreneurship",
    "food-booze",
    "life",
    "tech-ai",
    "trading",
)

# The blog root. Posts, category landings and the hub all live under it.
_BLOG_ROOT = "blogs"

# Single-segment allow-list (paths that are real first-level sections / pages).
# /tags/<slug>/ and /series/<slug>/ are taxonomy term pages auto-generated by
# Hugo from frontmatter; their existence cannot be checked from the markdown
# tree alone, so we accept them by allow-list.
_ALLOW_SINGLE = frozenset(
    [
        "",  # bare "/"
        _BLOG_ROOT,  # /blogs/ hub (content/posts/_index.md)
        "hire-hoi",
        "skills",
        "about",
        "legal",  # /legal/ section index (consulting-ops#6 Phase 6)
        "community",  # /community/ section index (#43 Phase 1)
        "index.xml",
        "sitemap.xml",
    ]
)

# Two-segment allow-list prefixes (paths that take a slug after the first
# segment). /hire-hoi/ai-consultancy/<slug>/ is a content page bundle; /tags|series/<slug>/
# is a taxonomy term page; /<section>/index.xml is the per-section RSS feed
# Hugo emits for each _index.md.
_ALLOW_TWO_PREFIX = frozenset(["hire-hoi", "tags", "series", "legal", "community"])

# Pre-compiled patterns.
# Frontmatter block — everything between the first two `---` lines. Used to read
# a post's `slug:` override without pulling in a YAML dependency (this script is
# a `language: system` pre-commit hook, so it stays stdlib-only).
_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.S)
_FM_SLUG_RE = re.compile(r"^slug:\s*(.+?)\s*$", re.M)
# Shortcode strip — Hugo shortcodes look like `{{< name args >}}` or `{{% ... %}}`.
_SHORTCODE_RE = re.compile(r"\{\{[<%].*?[>%]\}\}", re.DOTALL)
# HTML comment strip.
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
# Code fence strip — triple-backtick blocks (with or without language hint).
_CODE_FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
# Inline code strip — single-backtick spans on a line.
_INLINE_CODE_RE = re.compile(r"`[^`\n]+`")
# Self-reference normalisation — strip absolute hoiboy.uk prefix to leave a
# relative path. Catches absolute-style cross-references that would otherwise
# be skipped by the external-URL filter.
_SELF_REF_RE = re.compile(r"^https?://(www\.)?hoiboy\.uk", re.IGNORECASE)
# Inline link extractor — `[text](/path)` or `[text](/path "title")`.
# `(?<!!)` negative lookbehind excludes images `![alt](path)` (image existence
# is a different bug class — sibling-file in page bundle — out of scope).
_INLINE_LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(\s*(\S+?)(?:\s+\"[^\"]*\")?\s*\)")
# Reference-style link definition — `[ref]: /path` (standalone line; URL up to
# whitespace; optional title ignored).
_REF_DEF_RE = re.compile(r"^\s*\[([^\]]+)\]:\s*(\S+)", re.MULTILINE)
# Reference-style link usage — `[text][ref]` (collapsed `[text][]` also matches
# with ref==text).
_REF_USE_RE = re.compile(r"(?<!!)\[([^\]]+)\]\[([^\]]*)\]")
# Reference-style IMAGE usage — `![alt][ref]` (collapsed `![ref][]` also
# matches with ref==alt). Image existence is a different bug class
# (sibling-file in page bundle, out of scope), so refs used ONLY as images
# must be excluded from URL classification — the same out-of-scope decision
# the inline `(?<!!)` lookbehind makes for `![alt](path)`.
_REF_IMG_USE_RE = re.compile(r"!\[([^\]]*)\]\[([^\]]*)\]")


def _strip_non_link_regions(text: str) -> str:
    """Remove regions that should never contribute links: shortcodes,
    HTML comments, code fences, inline code. Order matters — fences first so
    inline-code stripping doesn't mangle fence interiors."""
    text = _CODE_FENCE_RE.sub("", text)
    text = _HTML_COMMENT_RE.sub("", text)
    text = _SHORTCODE_RE.sub("", text)
    text = _INLINE_CODE_RE.sub("", text)
    return text


def _line_of(text: str, offset: int) -> int:
    """1-based line number of the character at ``offset``."""
    return text.count("\n", 0, offset) + 1


def _normalise_target(raw: str) -> str | None:
    """Resolve a raw href into a normalised internal path, or None if the
    href is external / anchor-only / unsupported (skip)."""
    target = raw.strip()
    if not target:
        return None
    # Strip trailing fragment (anchor) — fragment irrelevant to path resolution.
    if "#" in target:
        target = target.split("#", 1)[0]
        if not target:
            return None  # pure anchor ](#section)
    # Strip trailing query string.
    if "?" in target:
        target = target.split("?", 1)[0]
        if not target:
            return None
    # Self-reference normalisation — absolute hoiboy.uk URL becomes relative.
    target = _SELF_REF_RE.sub("", target)
    # mailto / external — skip.
    if target.startswith(("mailto:", "tel:", "http://", "https://")):
        return None
    # Internal links MUST start with / (relative-path links to siblings are
    # not used in this codebase; if they appear, treat as out-of-scope skip
    # rather than false positive).
    if not target.startswith("/"):
        return None
    return target


@lru_cache(maxsize=None)
def _served_post_slugs(repo_root: Path) -> frozenset[str]:
    """Every slug the posts section actually SERVES, i.e. the ``<slug>`` in
    ``/blogs/<slug>/``.

    Hugo resolves it with ``:slugorcontentbasename`` (``config/_default/hugo.toml``
    ``[permalinks.page]``): a frontmatter ``slug:`` wins, else the bundle
    directory name. 2 of the 79 posts override it
    (``2026-04-07-foundation`` -> ``foundation``, ``ai-jargon-for-noobs`` ->
    ``ai-jargon-for-newbies``), so resolving on the directory name alone would
    reject a correct link to either AND accept a dead one — in both directions,
    the opposite of what the page serves.

    Read from the frontmatter block only (between the first two ``---`` lines),
    so a ``slug:`` mentioned in body prose cannot hijack it.
    """
    slugs: set[str] = set()
    for index in sorted((repo_root / "content" / "posts").glob("*/index.md")):
        slug = ""
        fm = _FRONTMATTER_RE.match(index.read_text(encoding="utf-8", errors="replace"))
        if fm:
            m = _FM_SLUG_RE.search(fm.group(1))
            if m:
                slug = m.group(1).strip().strip("\"'")
        slugs.add(slug or index.parent.name)
    return frozenset(slugs)


def _classify(target: str, repo_root: Path) -> tuple[bool, str]:
    """Return (ok, message). ``ok=True`` means the link passes; message is the
    error text when ``ok=False``."""
    # Trailing-slash normalisation: /blogs/foo and /blogs/foo/ are equivalent
    # (Hugo serves both — the path resolves to the same page bundle).
    stripped = target.strip("/")
    if stripped == "":
        return True, ""  # bare "/" — homepage.
    parts = stripped.split("/")
    first = parts[0]

    # --- the live blog tree -------------------------------------------------
    if first == _BLOG_ROOT:
        if len(parts) == 1:
            return True, ""  # the /blogs/ hub
        second = parts[1]
        if len(parts) == 2:
            if second == "index.xml" or second in _SECTIONS:
                return True, ""  # section feed, or a category landing
            if not second:
                return False, f"empty post slug in '{target}'"
            if second in _served_post_slugs(repo_root):
                return True, ""
            return False, (
                f"broken internal link: /{_BLOG_ROOT}/{second}/ is neither one of "
                f"the 7 category landings nor a post served at that slug "
                f"(a post's frontmatter `slug:` overrides its directory name)"
            )
        # /blogs/<category>/index.xml — per-category RSS feed.
        if len(parts) == 3 and second in _SECTIONS and parts[2] == "index.xml":
            return True, ""
        if second in _SECTIONS:
            slug = parts[2] if len(parts) > 2 and parts[2] else "<slug>"
            return False, (
                f"section-prefix link '{target}' — "
                f"category landings list posts, they don't host them. "
                f"Did you mean /{_BLOG_ROOT}/{slug}/?"
            )
        return False, f"unknown internal path '{target}'"

    # --- retired URL shapes (blog-priv#62) ----------------------------------
    # These still resolve for external visitors via the 301s in static/_redirects,
    # but an in-repo link should point at the live path rather than take the hop
    # (a redirected internal link is what AC 5.15 forbids).
    if first == "posts":
        rest = "/".join(parts[1:]).strip("/")
        suggestion = f"/{_BLOG_ROOT}/{rest}/" if rest else f"/{_BLOG_ROOT}/"
        return False, (
            f"retired URL '{target}' — posts moved to /{_BLOG_ROOT}/<slug>/. "
            f"Did you mean {suggestion}?"
        )
    if first in _SECTIONS:
        return False, (
            f"retired URL '{target}' — the 7 category landings moved under "
            f"/{_BLOG_ROOT}/. Did you mean /{_BLOG_ROOT}/{stripped}/?"
        )

    # --- everything else ----------------------------------------------------
    if len(parts) == 1:
        if first in _ALLOW_SINGLE:
            return True, ""
        return False, (
            f"unknown single-segment path '{target}' "
            f"(not blogs / hire-hoi / skills / about / legal / community / "
            f"index.xml / sitemap.xml)"
        )
    # /hire-hoi/ai-consultancy/<slug>/ — sub-page of the hire-hoi section.
    if first in _ALLOW_TWO_PREFIX:
        return True, ""
    return False, f"unknown internal path '{target}'"


def scan_file(md_path: Path, repo_root: Path) -> list[tuple[int, str, str]]:
    """Return a list of (line_number, target_link, error_message) for every
    invalid internal link in ``md_path``. Read errors raise; the caller
    catches and returns exit 2."""
    raw = md_path.read_text(encoding="utf-8")
    body = _strip_non_link_regions(raw)
    # Reference-style link definitions (parsed from the stripped body so we
    # don't pick up code-fenced examples).
    refs: dict[str, tuple[int, str]] = {}
    for m in _REF_DEF_RE.finditer(body):
        ref_id = m.group(1).strip().lower()
        url = m.group(2).strip()
        line = _line_of(body, m.start())
        refs[ref_id] = (line, url)
    # Track which refs are consumed by image syntax `![alt][ref]` vs link
    # syntax `[text][ref]`. Image-only refs are skipped from URL classification
    # because image existence is out of scope (parity with the inline `(?<!!)`
    # lookbehind that already excludes `![alt](path)`).
    image_refs: set[str] = set()
    for m in _REF_IMG_USE_RE.finditer(body):
        alt = m.group(1).strip().lower()
        ref_id = m.group(2).strip().lower() or alt  # collapsed `![ref][]`
        image_refs.add(ref_id)
    link_refs: set[str] = set()
    for m in _REF_USE_RE.finditer(body):
        text = m.group(1).strip().lower()
        ref_id = m.group(2).strip().lower() or text  # collapsed `[text][]`
        link_refs.add(ref_id)
    findings: list[tuple[int, str, str]] = []
    seen: set[tuple[int, str]] = set()
    # Inline `[text](/path)` links.
    for m in _INLINE_LINK_RE.finditer(body):
        raw_target = m.group(1)
        line = _line_of(body, m.start())
        target = _normalise_target(raw_target)
        if target is None:
            continue
        ok, msg = _classify(target, repo_root)
        if not ok and (line, target) not in seen:
            seen.add((line, target))
            findings.append((line, target, msg))
    # Reference-style link usages — resolve ref → URL via the definitions
    # table, then classify. Skip refs consumed only as images (see image_refs
    # above).
    for ref_id in link_refs:
        if ref_id not in refs:
            continue  # unknown ref — markdown renders it as literal text, not a link
        ref_line, ref_url = refs[ref_id]
        target = _normalise_target(ref_url)
        if target is None:
            continue
        ok, msg = _classify(target, repo_root)
        if not ok and (ref_line, target) not in seen:
            seen.add((ref_line, target))
            findings.append((ref_line, target, msg))
    # Reference-style definitions whose URL is itself broken AND the ref is
    # used as a link (or unused — defensive: an unused link-shaped def is a
    # latent bug). Skip image-only refs (out of scope, parity with inline
    # image lookbehind).
    for ref_id, (line, url) in refs.items():
        if ref_id in image_refs and ref_id not in link_refs:
            continue
        target = _normalise_target(url)
        if target is None:
            continue
        ok, msg = _classify(target, repo_root)
        if not ok and (line, target) not in seen:
            seen.add((line, target))
            findings.append((line, target, msg))
    findings.sort(key=lambda t: (t[0], t[1]))
    return findings


def _walk_content(repo_root: Path) -> list[Path]:
    """Walk ``content/**/*.md`` returning a sorted list of paths."""
    content = repo_root / "content"
    if not content.is_dir():
        raise FileNotFoundError(f"content/ not found at {content}")
    return sorted(content.rglob("*.md"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate internal markdown links for hoiboy.uk."
    )
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        help="Specific markdown files to scan. Omit to scan content/**/*.md.",
    )
    parser.add_argument(
        "--check-only-new",
        action="store_true",
        help=(
            "Accepted for parity with sibling validators. Internal-link rules "
            "do not depend on the HOIBOY_CUTOFF_DATE so this flag is a no-op."
        ),
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repo root (default: parent of scripts/).",
    )
    args = parser.parse_args()
    _ = args.check_only_new  # acknowledge — no behavioural difference.
    repo_root = args.repo_root.resolve()
    try:
        files = list(args.paths) if args.paths else _walk_content(repo_root)
    except FileNotFoundError as exc:
        print(f"validate_internal_links: {exc}", file=sys.stderr)
        return 2
    total = 0
    for md in files:
        try:
            findings = scan_file(md, repo_root)
        except OSError as exc:
            print(f"validate_internal_links: read error: {md}: {exc}", file=sys.stderr)
            return 2
        for line, target, msg in findings:
            try:
                rel = md.resolve().relative_to(repo_root)
            except ValueError:
                rel = md
            print(f"{rel}:{line}: {msg}", file=sys.stderr)
            total += 1
    if total:
        print(
            f"validate_internal_links: {total} broken internal link(s) found.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
