#!/usr/bin/env python3
"""Validate internal markdown links against the Hugo permalink contract.

Posts live at ``/posts/<slug>/`` (Hugo permalink for the ``posts`` section).
Section landings (``/dance/``, ``/food-booze/``, ...) are auto-generated
index pages — they LIST posts, they don't HOST them. A link of the form
``/dance/some-post/`` is therefore broken even though it looks plausible.

Lychee cannot catch this bug class: ``lychee.toml`` excludes
``content/posts`` (raw-markdown false-positive avoidance) and excludes
``hoiboy.uk`` URLs (Cloudflare race protection), so broken in-content
links to nonexistent ``/<section>/<slug>/`` paths are structurally
invisible to the existing link checker. This validator closes that gap.

Decision matrix (default = PASS):
  link is anchor-only / mailto / external / shortcode internals -> SKIP
  link path is /posts/<slug>/ AND content/posts/<slug>/ exists  -> PASS
  link path matches an allow-list entry                         -> PASS
  link path matches /<category>/<slug>/ with 2+ segments        -> FAIL
  link path is /posts/<slug>/ AND post bundle missing           -> FAIL
  any other / unrecognised internal path                        -> FAIL

Exit codes: 0 = pass, 1 = violations, 2 = read error
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Sections defined by config/_default/hugo.toml [taxonomies] + content/ tree
# (verified at config-traceability time — see Engineering Requirements).
_SECTIONS = (
    "adventure",
    "dance",
    "entrepreneurship",
    "food-booze",
    "life",
    "tech-ai",
    "trading",
)

# Single-segment allow-list (paths that are real first-level sections / pages).
# /tags/<slug>/ and /series/<slug>/ are taxonomy term pages auto-generated by
# Hugo from frontmatter; their existence cannot be checked from the markdown
# tree alone, so we accept them by allow-list.
_ALLOW_SINGLE = frozenset(
    [
        "",  # bare "/"
        "consulting",
        "skills",
        "about",
        "index.xml",
        "sitemap.xml",
    ]
    + list(_SECTIONS)
)

# Two-segment allow-list prefixes (paths that take a slug after the first
# segment). /consulting/<slug>/ is a content page bundle; /tags|series/<slug>/
# is a taxonomy term page; /<section>/index.xml is the per-section RSS feed
# Hugo emits for each _index.md.
_ALLOW_TWO_PREFIX = frozenset(["consulting", "tags", "series"])

# Pre-compiled patterns.
# Shortcode strip — Hugo shortcodes look like `{{< name args >}}` or `{{% ... %}}`.
_SHORTCODE_RE = re.compile(r"\{\{[<%].*?[>%]\}\}", re.DOTALL)
# HTML comment strip.
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
# Code fence strip — triple-backtick blocks (with or without language hint).
_CODE_FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
# Inline code strip — single-backtick spans on a line.
_INLINE_CODE_RE = re.compile(r"`[^`\n]+`")
# Self-reference normalisation — strip absolute hoiboy.uk prefix to leave a
# relative path. Catches absolute-style cross-references that would otherwise
# be skipped by the external-URL filter.
_SELF_REF_RE = re.compile(r"^https?://(www\.)?hoiboy\.uk", re.IGNORECASE)
# Inline link extractor — `[text](/path)` or `[text](/path "title")`.
# `(?<!!)` negative lookbehind excludes images `![alt](path)` (image existence
# is a different bug class — sibling-file in page bundle — out of scope).
_INLINE_LINK_RE = re.compile(r"(?<!!)\[[^\]]*\]\(\s*(\S+?)(?:\s+\"[^\"]*\")?\s*\)")
# Reference-style link definition — `[ref]: /path` (standalone line; URL up to
# whitespace; optional title ignored).
_REF_DEF_RE = re.compile(r"^\s*\[([^\]]+)\]:\s*(\S+)", re.MULTILINE)
# Reference-style link usage — `[text][ref]` (collapsed `[text][]` also matches
# with ref==text).
_REF_USE_RE = re.compile(r"(?<!!)\[([^\]]+)\]\[([^\]]*)\]")


def _strip_non_link_regions(text: str) -> str:
    """Remove regions that should never contribute links: shortcodes,
    HTML comments, code fences, inline code. Order matters — fences first so
    inline-code stripping doesn't mangle fence interiors."""
    text = _CODE_FENCE_RE.sub("", text)
    text = _HTML_COMMENT_RE.sub("", text)
    text = _SHORTCODE_RE.sub("", text)
    text = _INLINE_CODE_RE.sub("", text)
    return text


def _line_of(text: str, offset: int) -> int:
    """1-based line number of the character at ``offset``."""
    return text.count("\n", 0, offset) + 1


def _normalise_target(raw: str) -> str | None:
    """Resolve a raw href into a normalised internal path, or None if the
    href is external / anchor-only / unsupported (skip)."""
    target = raw.strip()
    if not target:
        return None
    # Strip trailing fragment (anchor) — fragment irrelevant to path resolution.
    if "#" in target:
        target = target.split("#", 1)[0]
        if not target:
            return None  # pure anchor ](#section)
    # Strip trailing query string.
    if "?" in target:
        target = target.split("?", 1)[0]
        if not target:
            return None
    # Self-reference normalisation — absolute hoiboy.uk URL becomes relative.
    target = _SELF_REF_RE.sub("", target)
    # mailto / external — skip.
    if target.startswith(("mailto:", "tel:", "http://", "https://")):
        return None
    # Internal links MUST start with / (relative-path links to siblings are
    # not used in this codebase; if they appear, treat as out-of-scope skip
    # rather than false positive).
    if not target.startswith("/"):
        return None
    return target


def _resolve_post_bundle(repo_root: Path, slug: str) -> bool:
    """True iff content/posts/<slug>/index.md exists."""
    return (repo_root / "content" / "posts" / slug / "index.md").is_file()


def _classify(target: str, repo_root: Path) -> tuple[bool, str]:
    """Return (ok, message). ``ok=True`` means the link passes; message is the
    error text when ``ok=False``."""
    # Trailing-slash normalisation: /posts/foo and /posts/foo/ are equivalent
    # (Hugo serves both — the path resolves to the same page bundle).
    stripped = target.strip("/")
    if stripped == "":
        return True, ""  # bare "/" — homepage.
    parts = stripped.split("/")
    first = parts[0]
    # Single-segment paths.
    if len(parts) == 1:
        if first in _ALLOW_SINGLE:
            return True, ""
        return False, (
            f"unknown single-segment path '{target}' "
            f"(not a section / consulting / skills / tags / series / index.xml / sitemap.xml)"
        )
    # /posts/<slug>/ — verify the page bundle exists.
    if first == "posts":
        if len(parts) < 2 or not parts[1]:
            return False, f"empty post slug in '{target}'"
        slug = parts[1]
        if not _resolve_post_bundle(repo_root, slug):
            return False, (
                f"broken internal link: /posts/{slug}/ has no content/posts/{slug}/index.md"
            )
        return True, ""
    # /<section>/index.xml — per-section RSS feed (Hugo emits one per _index.md).
    if first in _SECTIONS and len(parts) == 2 and parts[1] == "index.xml":
        return True, ""
    # /<section>/<slug>/ — section-prefix bug. The whole point of this validator.
    if first in _SECTIONS:
        slug = parts[1] if parts[1] else "<slug>"
        return False, (
            f"section-prefix link '{target}' — "
            f"section landings list posts, they don't host them. "
            f"Did you mean /posts/{slug}/?"
        )
    # /consulting/<slug>/ — sub-page of consulting.
    if first in _ALLOW_TWO_PREFIX:
        return True, ""
    return False, f"unknown internal path '{target}'"


def scan_file(md_path: Path, repo_root: Path) -> list[tuple[int, str, str]]:
    """Return a list of (line_number, target_link, error_message) for every
    invalid internal link in ``md_path``. Read errors raise; the caller
    catches and returns exit 2."""
    raw = md_path.read_text(encoding="utf-8")
    body = _strip_non_link_regions(raw)
    # Reference-style link definitions (parsed from the stripped body so we
    # don't pick up code-fenced examples).
    refs: dict[str, tuple[int, str]] = {}
    for m in _REF_DEF_RE.finditer(body):
        ref_id = m.group(1).strip().lower()
        url = m.group(2).strip()
        line = _line_of(body, m.start())
        refs[ref_id] = (line, url)
    findings: list[tuple[int, str, str]] = []
    seen: set[tuple[int, str]] = set()
    # Inline `[text](/path)` links.
    for m in _INLINE_LINK_RE.finditer(body):
        raw_target = m.group(1)
        line = _line_of(body, m.start())
        target = _normalise_target(raw_target)
        if target is None:
            continue
        ok, msg = _classify(target, repo_root)
        if not ok and (line, target) not in seen:
            seen.add((line, target))
            findings.append((line, target, msg))
    # Reference-style usages `[text][ref]` — resolve ref → URL via the
    # definitions table, then classify.
    for m in _REF_USE_RE.finditer(body):
        text = m.group(1).strip().lower()
        ref_id = m.group(2).strip().lower() or text  # collapsed `[text][]`
        if ref_id not in refs:
            continue  # unknown ref — markdown renders it as literal text, not a link
        ref_line, ref_url = refs[ref_id]
        target = _normalise_target(ref_url)
        if target is None:
            continue
        ok, msg = _classify(target, repo_root)
        if not ok and (ref_line, target) not in seen:
            seen.add((ref_line, target))
            findings.append((ref_line, target, msg))
    # Reference-style definitions whose URL is itself broken (e.g. a `[ref]:
    # /dance/foo/` line that no `[text][ref]` ever uses — still a buggy
    # reference that would fail when activated).
    for ref_id, (line, url) in refs.items():
        target = _normalise_target(url)
        if target is None:
            continue
        ok, msg = _classify(target, repo_root)
        if not ok and (line, target) not in seen:
            seen.add((line, target))
            findings.append((line, target, msg))
    findings.sort(key=lambda t: (t[0], t[1]))
    return findings


def _walk_content(repo_root: Path) -> list[Path]:
    """Walk ``content/**/*.md`` returning a sorted list of paths."""
    content = repo_root / "content"
    if not content.is_dir():
        raise FileNotFoundError(f"content/ not found at {content}")
    return sorted(content.rglob("*.md"))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate internal markdown links for hoiboy.uk."
    )
    parser.add_argument(
        "paths",
        nargs="*",
        type=Path,
        help="Specific markdown files to scan. Omit to scan content/**/*.md.",
    )
    parser.add_argument(
        "--check-only-new",
        action="store_true",
        help=(
            "Accepted for parity with sibling validators. Internal-link rules "
            "do not depend on the HOIBOY_CUTOFF_DATE so this flag is a no-op."
        ),
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repo root (default: parent of scripts/).",
    )
    args = parser.parse_args()
    _ = args.check_only_new  # acknowledge — no behavioural difference.
    repo_root = args.repo_root.resolve()
    try:
        files = list(args.paths) if args.paths else _walk_content(repo_root)
    except FileNotFoundError as exc:
        print(f"validate_internal_links: {exc}", file=sys.stderr)
        return 2
    total = 0
    for md in files:
        try:
            findings = scan_file(md, repo_root)
        except OSError as exc:
            print(f"validate_internal_links: read error: {md}: {exc}", file=sys.stderr)
            return 2
        for line, target, msg in findings:
            try:
                rel = md.resolve().relative_to(repo_root)
            except ValueError:
                rel = md
            print(f"{rel}:{line}: {msg}", file=sys.stderr)
            total += 1
    if total:
        print(
            f"validate_internal_links: {total} broken internal link(s) found.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
